export const CORRECT_GUESS = `CORRECT_GUESS`
export const ADD_GUESSED_WORD = `ADD_GUESSED_WORD`
export const SET_SECRET_WORD = `SET_SECRET_WORD`
export const RESET_SUCCESS = `RESET_SUCCESS`
export const RESET_GUESSED_WORDS = `RESET_GUESSED_WORDS`
